/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testDefaultImage1(){

        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        String s0 = classloader.getResource("image1.bmp").toString();
        String DefaultInputPath = s0.replace("file:/C", "C");
        ;
        String s1 = classloader.getResource("").toString() + "/newImage.bmp";
        String DefaultOutPutPath = s1.replace("file:/C", "C").toString().replace("build/classes/java/main/", "src/main/resources");
        Bitmap TEST = new Bitmap("/mnt/c/Users/M.2070/MyWork/bitmap-transformer/app/src/main/resources/image1.bmp", "/mnt/c/Users/M.2070/MyWork/bitmap-transformer/app/src/main/resources/" +"BlackAndWhite.bmp", "BlackAndWhite");
assertEquals(1,TEST.BlackAndWhite());

    }
    @Test
    void testDefaultImage2(){

        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        String s0 = classloader.getResource("image1.bmp").toString();
        String DefaultInputPath = s0.replace("file:/C", "C");

        String s1 = classloader.getResource("").toString() + "/newImage.bmp";
        String DefaultOutPutPath = s1.replace("file:/C", "C").toString().replace("build/classes/java/main/", "src/main/resources");
        Bitmap TEST = new Bitmap("/mnt/c/Users/M.2070/MyWork/bitmap-transformer/app/src/main/resources/image1.bmp", "/mnt/c/Users/M.2070/MyWork/bitmap-transformer/app/src/main/resources/"+"PixiLate.bmp", "PixiLate");
        assertEquals(1,TEST.PixiLate(10));

    }
    @Test
    void testDefaultImage3(){

        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        String s0 = classloader.getResource("image1.bmp").toString();
        String DefaultInputPath = s0.replace("file:/C", "C");
        ;
        String s1 = classloader.getResource("").toString() + "/newImage.bmp";
        String DefaultOutPutPath = s1.replace("file:/C", "C").toString().replace("build/classes/java/main/", "src/main/resources");

        Bitmap TEST = new Bitmap("/mnt/c/Users/M.2070/MyWork/bitmap-transformer/app/src/main/resources/image1.bmp", "/mnt/c/Users/M.2070/MyWork/bitmap-transformer/app/src/main/resources/" +"Rotate.bmp", "Rotate", 90);
        assertEquals(1,TEST.Rotate(90));

    }
}
