/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;
import java.util.concurrent.TimeoutException;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) throws IOException, TimeoutException {
//        showResult(); // Call this function to show Result;


if (args.length>2) {

        Bitmap TEST = new Bitmap(args[0] ,args[1], args[2]);
}

}

static void showResult(){

    ClassLoader classloader = Thread.currentThread().getContextClassLoader();
    String s0 = classloader.getResource("image1.bmp").toString();
    String DefaultInputPath = s0.replace("file:/C", "C");
    ;
    String s1 = classloader.getResource("").toString() + "/newImage.bmp";
    String DefaultOutPutPath = s1.replace("file:/C", "C").toString().replace("build/classes/java/main/", "src/main/resources");
    Bitmap TEST = new Bitmap(DefaultInputPath, DefaultOutPutPath, "Rotate", 180);
}



}

